### ISSUE TITLE
Mix form and openid connect authentication

### ISSUE THREAD

**Issue by amergey** [boylesoftware/tomcat8-oidcauth#1]
In previous version of OpenID connector (the OpenID 2.0 connector)
It was possible to combine Open ID and Form authentication (see Login page part of https://www.boylesoftware.com/wiki/index.php/OpenID_Authenticator_for_Tomcat)
According to documentation It seems, with OpenID connect connector, it is not possible anymore, am I right ?

**Comment by levahim** [comment]
That's correct. At least for the moment.

**Comment by levahim** [comment]
Support for form-based and multiple OPs authentication is now implemented in release 2.0.
