### ISSUE TITLE
Problem using valve in Tomcat 8.5.6

### ISSUE THREAD

**Issue by jeffemandel** [boylesoftware/tomcat8-oidcauth#2]
I am trying to get your org.bsworks.catalina.authenticator.oidc package to work without much luck. I have Ubuntu 16.04, Tomcat 8.5.6, java-7-openjdk-amd64. I am using version 1.01 of your package.

In conf/context.xml:

	<Valve className="org.bsworks.catalina.authenticator.oidc.OpenIDConnectAuthenticator"
		discoveryDocumentURL="https://accounts.google.com/.well-known/openid-configuration"
		clientId="XXX.apps.googleusercontent.com"
		clientSecret="XXX"
		hostedDomain="example.com"
		usernameClaim="email"/>

I have the webapp web.xml configured for FORM authentication, and a JDBCRealm set up for my Postgresql database. When I point my browser at the server, it goes straight to my login.html page, and I can authenticate using the FormAuthenticator. Looking at catalina.out (having set logging to FINE), I see:

```
15-Nov-2016 08:48:37.507 FINE [localhost-startStop-1] org.bsworks.catalina.authenticator.oidc.OpenIDConnectAuthenticator.httpGet getting data from https://accounts.google.com/.well-known/openid-configuration
15-Nov-2016 08:48:39.606 FINE [localhost-startStop-1] org.bsworks.catalina.authenticator.oidc.OpenIDConnectAuthenticator.httpGet received response: {
 "issuer": "https://accounts.google.com", ...

```
but no other messages from org.bsworks.catalina.authenticator.oidc.OpenIDConnectAuthenticator. I even added a statement to the source to log "Alive" on entry to authenticate. This produces no output. I'm not understanding why startInternal() is getting called, but authenticate is not.

Note, updating to 8.5.x requires adding this dependency:
```
<!-- https://mvnrepository.com/artifact/javax.security.auth.message/javax.security.auth.message-api -->
<dependency>
    <groupId>javax.security.auth.message</groupId>
    <artifactId>javax.security.auth.message-api</artifactId>
    <version>1.1</version>
</dependency>

```
Thanks,
Jeff E Mandel MD MS

**Comment by levahim** [comment]
This authenticator was never tested with Tomcat 8.5. Would you be able to see if it works as expected in Tomcat 8.0? There could be a change in the protocol between the two versions. If so, we may be able to release an update next week to make it work for the 8.5.

**Comment by jeffemandel** [comment]
I tried it under Tomcat 8.0.39, and it works (well, it fails, but with a Google 400 page). Everything (conf/server.xml, conf/context.xml, and the webapp) are the same, so it looks like an 8.5 issue. I don’t really need features of 8.5, but best to be current.

BTW, is there a way to insist that the user have a second factor in their Google account?

Thanks,

Jeff

**Comment by jeffemandel** [comment]
Any progress on this?

**Comment by levahim** [comment]
There is a branch tomcat85. If you check it out and compile the authenticator jar from it it'll work with Tomcat 8.5.

**Comment by jeffemandel** [comment]
Thanks!

Jeff
