### ISSUE TITLE
Add access token to header

### ISSUE THREAD

**Issue by dileep55** [boylesoftware/tomcat8-oidcauth#3]
Any plans to add the access token to the header. This could be useful for applications as they move to use OIDC and leverage access token for access.

**Comment by levahim** [comment]
Please clarify your request.

**Comment by dileep55** [comment]
As part of the request, we get the access and ID tokens. The access token needs to be passed by the Apps when making a protected API call. So if apps have the ability to get the access token via header then it would help apps call protected API's

**Comment by levahim** [comment]
Ok, I think I got it. This authenticator is made for "traditional" web-apps that generate pages on the server side (e.g. JSPs) and not for the apps that make AJAX calls to the APIs from the browser. So, all aspects of the authentication process are hidden on the server side. This authenticator also attempts to hide the fact that it uses OpenID Connect and allow the web-apps to be developed compatible with normal form-based authentication, so the app can be deployed either with form-based auth or this OIDC auth without any changes.

Having said that, the new release that's coming soon will have the token endpoint's response object saved in the HTTP session, so a web-app could include stuff like id token and access token in the pages/responses that it sends back to the caller. That would be your solution, but beware of the security implications exposing these tokens in the communication between the server and the browser.

**Comment by levahim** [comment]
In the new 2.0 release the authorization information, including the access token, are now available in the HTTP session.
