### ISSUE TITLE
Tomcat 8.5 compatible release

### ISSUE THREAD

**Issue by amergey** [boylesoftware/tomcat8-oidcauth#4]
Hello,
I see there is a branch where changes has been made to make the connector compatible to tomcat 85,
is there any jar available from maven ?

**Comment by levahim** [comment]
Hi. No, no jar in Maven at the moment. You'd have to clone the repo and build the package. We are looking into reorganizing this project so that it builds both 80 and 85 versions and publishes them in Maven.

**Comment by amergey** [comment]
tomcat 80 will not be necessary because it is reaching its end of life soon

**Comment by levahim** [comment]
Good point. We'll merge the 85 branch into the master and make a release.
