### ISSUE TITLE
Support custom scope for ADFS custom claim

### ISSUE THREAD

**Issue by amergey** [boylesoftware/tomcat8-oidcauth#5]
Hello,
On ADFS 2016 it is possible to configure some custom claims with OpenID Connect sign-in,
but it is necessary to send a custom scope. 
On https://github.com/boylesoftware/tomcat8-oidcauth/blob/master/src/main/java/org/bsworks/catalina/authenticator/oidc/OpenIDConnectAuthenticator.java line 518, scope is hardcoded. 

would it be possible to add a configuration for this (as userNameClaim) ? 
I can do a pull request if you want

**Comment by levahim** [comment]
We are preparing a long due new revised/refreshed release of this module in a few days, phasing out 8.0 support from the main branch. Configurable login name claim is going to a part of it.

**Comment by levahim** [comment]
The new 2.0 release now includes "additionalScopes" attribute in the authenticator configuration.
