### ISSUE TITLE
Tomcat 8.5.5 - Problem authenticating with Okta

### ISSUE THREAD

**Issue by Vengat** [boylesoftware/tomcat8-oidcauth#6]
This is my context.xml

`<Valve className="org.bsworks.catalina.authenticator.oidc.tomcat85.OpenIDConnectAuthenticator"
       providers="[
           {
               name: 'OKTA',
               issuer: https://okta-domain.com/oauth2/default,
	      configurationDocumentUrl: https://okta-domain.com/oauth2/default/.well-known/oauth-authorization-server,
               clientId: ,
               clientSecret:  
           },
        
       ]"
	   
       usernameClaim="email" additionalScopes="email" noForm="true"/>`

I am getting a 401 response. This is the exact response.

> FINE [https-openssl-nio-8443-exec-4] org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.callTokenEndpoint received response: status: 401, date: 4 Jun, 2018 10:55:29 AM, body: {"error_description":"Cannot supply multiple client credentials. Use one of the following: credentials in the Authorization header, credentials in the post body, or a client_assertion in the post body.","error":"invalid_request"}

I tried removing the client secret but that too came back with client not recognised

**Comment by levahim** [comment]
Thanks for reporting. Never tested it with Okta. Will look into it...

**Comment by levahim** [comment]
Fixed in release 2.2.1. It now works with Okta as well.

**Comment by Vengat** [comment]
Thanks a lot
