### ISSUE TITLE
Authenticator is looking for user in the realm

### ISSUE THREAD

**Issue by Vengat** [boylesoftware/tomcat8-oidcauth#7]
> 06-Jun-2018 16:03:17.655 FINE [https-openssl-nio-8443-exec-8] org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.processAuthResponse failed to authenticate the user in the realm

I am not sure if this can be categorised as a bug. I have read this:

> Once the authenticator exchanges the authoization code for the ID Token, it extracts a field from the token (a claim) used as the username in the Tomcat's Realm and looks up the user. If the user is found in the realm, the user becomes the authenticated user and the HTTP session becomes authenticated.

Do we have to provide the claim/username in the memory realm? 

For example:

`<role rolename="user"/>
<user username="vengat.r@test.com" password="" roles="user"/>`

This works fine.

It would be difficult to scale by adding users like this in the MemoryRealm. I have no DB of users/passwords so I cant use JDBC/DataSourceRealm.

Will the authenticator look up the user from the JNDI realm? Is there a specific configuration to let the authenticator look up a user in the JNDI realm (LDAP)? I have LDAP set up in other environments.

I was of the understanding that when the authenticator exchanges the authorization code for the ID token, the whole process would end there.

**Comment by levahim** [comment]
Yes, you need a realm. In Tomcat architecture the authenticator and the realm are two separate components. And yes, you can use an LDAP realm (see http://tomcat.apache.org/tomcat-8.5-doc/realm-howto.html#JNDIRealm), configure a JAAS realm (see http://tomcat.apache.org/tomcat-8.5-doc/realm-howto.html#JAASRealm) that always authenticates, or you can write your own "stub" realm that simply always returns the authenticated user.
