### ISSUE TITLE
Encoding of secret keys with special charachters in

### ISSUE THREAD

**Issue by edthompson** [boylesoftware/tomcat8-oidcauth#9]
We noticed that Microsoft occasional will create a secret key with a plus sign in (+). 
This causes the oauth process to fail with a key error. If we URL encode the key in the valve config  this solves the problem however we are persisting an encoded secret rather than the actual secret which can be confusing.

Should the key secret be encoded before its sent to the Auth Provider?

**Comment by levahim** [comment]
Could you please provide more detail about the error that you're seeing? Stack traces, error messages that you're seeing, etc. The only place where the client secret is sent to the provider is the token endpoint when client_secret_post authentication is used and in that case the client secret is already URL-encoded (see BaseOpenIDConnectAuthenticator.java line 1554).

**Comment by weiganglin** [comment]
Thanks for your reply.
when I using the client secret that contains + sign for Microsoft, I am getting the following error:
`18-Jun-2018 07:58:10.946 FINE [https-openssl-apr-8443-exec-9] org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.processAuthResponse authenticating user using OpenID Connect authentication response
18-Jun-2018 07:58:10.946 FINE [https-openssl-apr-8443-exec-9] org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.processAuthResponse processing authentication response from https://sts.windows.net/09d19996-a185-4b6c-8332-37120f9bba10/
18-Jun-2018 07:58:10.948 FINE [https-openssl-apr-8443-exec-9] org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.callTokenEndpoint calling token endpoint at https://login.windows.net/09d19996-a185-4b6c-8332-37120f9bba10/oauth2/token with: grant_type=authorization_code&code=AQABAAIAAADX8GCi6Js6SK82TsD2Pb7r6Xah_DXhxdzLf2S_7KGDoQPmuq5tHFb6aI86LWV8AicWHB20EF57ddX9sAITm8fdHtDxh6LYrqiqhBAnS0zHkFBVbUB7hY85QWkQUT6gCOQt42hTrUBZElMs-E9QRtj8RgH6UcW4pReWFYo8E5x3obT5TjWOyBIXbg1pUjLcFxsiLVaLZDxjiEN7ZgrjXR-SDWG49mby-XVLtHh0D4ULQdbAXmAdPHKrGTZ_W_7Gdf6MSABEMjByCPiqWGJglzNFj5UFR7xy_OxkO73z8OlAAqx_ylGUosE5xErgLoDpyfMNLeWabCUbra3WciiUtLe8gqMEQN-dOPcMe-16lekDYOMk2t4TYlh9Rccb1YulgOYfHPKJPgDi2E53TlKhofQpO7xUSPEiF4fj8d6E5gOZD8lM9IPVgjgn8f73riVIbANp91e03Zj2HbrLcvbLt1UM5w3-wApJZP35jBPQtBbHkECvbD-tquY1vEH5-gjPWEdQqLZjodrQwFPeKvlZ9EbFKIRBPFDN-CUI9nMf_mw_aPNsRt9sLMo8R6LdU2jMxgcgAA&redirect_uri=https%3A%2F%2F10.12.5.85%3A36440%2Fj_security_check&client_id=af5b153d-42e5-447a-ac98-d2bb1d7afb9f
18-Jun-2018 07:58:11.206 FINE [https-openssl-apr-8443-exec-9] org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.callTokenEndpoint received response: status: 401, date: Jun 18, 2018 7:58:10 AM, body: {"trace_id":"df1a0191-e1b0-4fbe-a64c-4785486f2500","error_description":"AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.\r\nTrace ID: df1a0191-e1b0-4fbe-a64c-4785486f2500\r\nCorrelation ID: 9ba03f88-d0f7-4f18-8e86-48392920e0ad\r\nTimestamp: 2018-06-18 07:58:11Z","correlation_id":"9ba03f88-d0f7-4f18-8e86-48392920e0ad","error_codes":[70002,50012],"error":"invalid_client","timestamp":"2018-06-18 07:58:11Z"}
18-Jun-2018 07:58:11.207 FINE [https-openssl-apr-8443-exec-9] org.bsworks.catalina.authenticator.oidc.BaseOpenIDConnectAuthenticator.processAuthResponse token error response: invalid_client`

**Comment by levahim** [comment]
I have to classify this is a Microsoft bug. After reviewing all relevant specifications, the basic auth implementation on the Microsoft side should absolutely be able to handle a plus character in the password without any URL encoding, which is really inappropriate in this particular place. So, to workaround your issue, until Microsoft fixes their system, I see three practical workarounds:

1. URL-encode the client secret value in the authenticator valve configuration XML.

2. Regenerate the client secret and use one without a plus character.

3. Use client_secret_post token endpoint authentication method (by adding "tokenEndpointAuthMethod: client_secret_post" to your configuration).
